### ISSUE TITLE
[FEATURE REQUEST] - Live Chat

### ISSUE THREAD

**Issue by mhgorguk** [Mersey-Hosting-Hub/community.merseyhostinghub.co.uk#2]
**Is your feature request related to a problem? Please describe.**
Addition of a live chat service for Peer To Peer support and live staff chat, for help and support.

**Describe the solution you'd like**
Discord type chat.

**Describe alternatives you've considered**
HTML5 Chat

**Additional context**

**Comment by bambieuk** [comment]
Discussion added #4
